"""empty message

Revision ID: 20f9400aa8bd
Revises: 
Create Date: 2022-07-08 13:54:01.152700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f9400aa8bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drikkevann',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drikkevann_href'), 'drikkevann', ['href'], unique=True)
    op.create_table('dusj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dusj_href'), 'dusj', ['href'], unique=True)
    op.create_table('parkeringsområde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parkeringstilbyderNavn', sa.String(length=160), nullable=True),
    sa.Column('breddegrad', sa.NullType(), nullable=True),
    sa.Column('lengdegrad', sa.NullType(), nullable=True),
    sa.Column('deaktivert', sa.Boolean(), nullable=True),
    sa.Column('versjonsnumber', sa.Integer(), nullable=True),
    sa.Column('navn', sa.String(length=160), nullable=True),
    sa.Column('adresse', sa.String(length=160), nullable=True),
    sa.Column('postnummer', sa.Integer(), nullable=True),
    sa.Column('poststed', sa.String(length=160), nullable=True),
    sa.Column('aktiveringsTidspunkt', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parkeringsområde_adresse'), 'parkeringsområde', ['adresse'], unique=True)
    op.create_index(op.f('ix_parkeringsområde_aktiveringsTidspunkt'), 'parkeringsområde', ['aktiveringsTidspunkt'], unique=True)
    op.create_index(op.f('ix_parkeringsområde_navn'), 'parkeringsområde', ['navn'], unique=True)
    op.create_index(op.f('ix_parkeringsområde_parkeringstilbyderNavn'), 'parkeringsområde', ['parkeringstilbyderNavn'], unique=True)
    op.create_index(op.f('ix_parkeringsområde_poststed'), 'parkeringsområde', ['poststed'], unique=True)
    op.create_table('parkeringstilbyder',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('organisasjonsnummer', sa.Integer(), nullable=True),
    sa.Column('navn', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('navn')
    )
    op.create_index(op.f('ix_parkeringstilbyder_navn'), 'parkeringstilbyder', ['navn'], unique=True)
    op.create_table('rest_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('num_small_vehicle', sa.Integer(), nullable=True),
    sa.Column('num_big_vehicle', sa.Integer(), nullable=True),
    sa.Column('lokasjon', sa.String(length=160), nullable=True),
    sa.Column('href', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rest_areas_href'), 'rest_areas', ['href'], unique=True)
    op.create_index(op.f('ix_rest_areas_lokasjon'), 'rest_areas', ['lokasjon'], unique=True)
    op.create_index(op.f('ix_rest_areas_name'), 'rest_areas', ['name'], unique=True)
    op.create_index(op.f('ix_rest_areas_num_big_vehicle'), 'rest_areas', ['num_big_vehicle'], unique=True)
    op.create_index(op.f('ix_rest_areas_num_small_vehicle'), 'rest_areas', ['num_small_vehicle'], unique=True)
    op.create_table('strøm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strøm_href'), 'strøm', ['href'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strøm_href'), table_name='strøm')
    op.drop_table('strøm')
    op.drop_index(op.f('ix_rest_areas_num_small_vehicle'), table_name='rest_areas')
    op.drop_index(op.f('ix_rest_areas_num_big_vehicle'), table_name='rest_areas')
    op.drop_index(op.f('ix_rest_areas_name'), table_name='rest_areas')
    op.drop_index(op.f('ix_rest_areas_lokasjon'), table_name='rest_areas')
    op.drop_index(op.f('ix_rest_areas_href'), table_name='rest_areas')
    op.drop_table('rest_areas')
    op.drop_index(op.f('ix_parkeringstilbyder_navn'), table_name='parkeringstilbyder')
    op.drop_table('parkeringstilbyder')
    op.drop_index(op.f('ix_parkeringsområde_poststed'), table_name='parkeringsområde')
    op.drop_index(op.f('ix_parkeringsområde_parkeringstilbyderNavn'), table_name='parkeringsområde')
    op.drop_index(op.f('ix_parkeringsområde_navn'), table_name='parkeringsområde')
    op.drop_index(op.f('ix_parkeringsområde_aktiveringsTidspunkt'), table_name='parkeringsområde')
    op.drop_index(op.f('ix_parkeringsområde_adresse'), table_name='parkeringsområde')
    op.drop_table('parkeringsområde')
    op.drop_index(op.f('ix_dusj_href'), table_name='dusj')
    op.drop_table('dusj')
    op.drop_index(op.f('ix_drikkevann_href'), table_name='drikkevann')
    op.drop_table('drikkevann')
    # ### end Alembic commands ###
